pipeline
{
	agent any
	
	stages
	{
		stage("Compile State")
		{
		//jkhkjjkjk
			steps{
			withMaven(maven : 'apache-maven-3.6.0')
					{
					sh 'mvn clean compile'
					}
				}
		}
		stage("testing stage")
		{
			steps{
			withMaven(maven : 'apache-maven-3.6.0')
					{
					sh 'mvn test'
					}
			
				}
		}
		stage("testing stage")
		{
			steps{
			withMaven(maven : 'apache-maven-3.6.0')
					{
					sh 'mvn build'
					}
			
				}
		}
	
	}
}